In [1]:
import pandas as pd
import numpy as np

In [2]:
we = pd.read_csv(r'C:\Users\dharu\Documents\Studies\Q7\DS672\Data\Mer\w.csv')

In [3]:
ar = pd.read_csv(r'C:\Users\dharu\Documents\Studies\Q7\DS672\Data\Detailed_Statistics_Arrivals_Combined.csv')

C:\Users\dharu\AppData\Local\Continuum\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3058: DtypeWarning: Columns (2,7,8,9,11,12,13,14,15,16) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [7]:
ar

,Carrier Code,Date (MM/DD/YYYY),Flight Number,Tail Number,Origin Airport,Scheduled Arrival Time,Actual Arrival Time,Scheduled Elapsed Time (Minutes),Actual Elapsed Time (Minutes),Arrival Delay (Minutes),Wheels-on Time,Taxi-In time (Minutes),Delay Carrier (Minutes),Delay Weather (Minutes),Delay National Aviation System (Minutes),Delay Security (Minutes),Delay Late Aircraft Arrival (Minutes),Arrival Airport
0,AA,1/1/2016,232,N023AA,DFW,18:36,19:03,126,106,27,18:58,5,1,0,0,0,26,ATL
1,AA,1/1/2016,604,N542UW,CLT,10:48,10:42,78,74,-6,10:30,12,0,0,0,0,0,ATL
2,AA,1/1/2016,610,N580UW,PHX,15:38,15:14,223,196,-24,15:05,9,0,0,0,0,0,ATL
3,AA,1/1/2016,612,N640AW,PHX,18:57,18:34,212,191,-23,18:27,7,0,0,0,0,0,ATL
4,AA,1/1/2016,614,N663AW,PHX,21:50,21:31,210,196,-19,21:23,8,0,0,0,0,0,ATL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4245606,UA,12/31/20,2002,N489UA,IAD,11:22,11:01,147,136,-21,10:57,4,0,0,0,0,0,TPA
4245607,UA,12/31/20,2067,N38268,IAH,17:46,18:13,126,140,27,18:09,4,13,0,14,0,0,TPA
4245608,UA,12/31/20,2137,N37252,BOS,11:51,11:20,216,191,-31,11:18,2,0,0,0,0,0,TPA
4245609,UA,12/31/20,2145,N26226,DEN,13:23,13:07,204,195,-16,13:05,2,0,0,0,0,0,TPA
4245610,UA,12/31/20,2158,N37456,ORD,17:51,17:59,161,161,8,17:55,4,0,0,0,0,0,TPA

In [5]:
lst = ['ORD', 'JFK', 'ATL', 'IAH', 'LAS', 'LAX', 'SFO', 'IAD', 'TPA', 'RDU','LGA']
f_df = ar[ar['Origin Airport'].isin(lst)]

In [15]:
f_df.describe

<bound method NDFrame.describe of         Carrier Code Date (MM/DD/YYYY) Flight Number Tail Number  \
9                 AA          1/1/2016          1116      N005AA
11                AA          1/1/2016          1249      N027AA
20                AA          1/1/2016          2319      N4XBAA
23                AA          1/1/2016          2513      N020AA
34                AA          1/1/2017           909      N3FVAA
...              ...               ...           ...         ...
4245604           UA          12/31/20          1444      N75425
4245605           UA          12/31/20          1538      N69818
4245606           UA          12/31/20          2002      N489UA
4245607           UA          12/31/20          2067      N38268
4245610           UA          12/31/20          2158      N37456

        Origin Airport Scheduled Arrival Time Actual Arrival Time  \
9                  LAX                   6:13                5:57
11                 LAX                  17:17               17:15
20                 ORD                  21:35               21:25
23                 LAX                  23:15               23:18
34                 ORD                  17:56               17:50
...                ...                    ...                 ...
4245604            IAH                  20:21               20:10
4245605            ORD                  12:31               12:20
4245606            IAD                  11:22               11:01
4245607            IAH                  17:46               18:13
4245610            ORD                  17:51               17:59

        Scheduled Elapsed Time (Minutes) Actual Elapsed Time (Minutes)  \
9                                    253                           232
11                                   257                           248
20                                   121                           113
23                                   255                           227
34                                   116                           113
...                                  ...                           ...
4245604                              126                           114
4245605                              161                           155
4245606                              147                           136
4245607                              126                           140
4245610                              161                           161

        Arrival Delay (Minutes) Wheels-on Time Taxi-In time (Minutes)  \
9                           -16           5:48                      9
11                           -2          17:10                      5
20                          -10          21:08                     17
23                            3          23:12                      6
34                           -6          17:41                      9
...                         ...            ...                    ...
4245604                     -11          20:06                      4
4245605                     -11          12:16                      4
4245606                     -21          10:57                      4
4245607                      27          18:09                      4
4245610                       8          17:55                      4

        Delay Carrier (Minutes) Delay Weather (Minutes)  \
9                             0                       0
11                            0                       0
20                            0                       0
23                            0                       0
34                            0                       0
...                         ...                     ...
4245604                       0                       0
4245605                       0                       0
4245606                       0                       0
4245607                      13                       0
4245610                       0                       0

        Delay National Aviation System (Minutes) Delay Security (Minutes)  \
9                                              0                        0
11                                             0                        0
20                                             0                        0
23                                             0                        0
34                                             0                        0
...                                          ...                      ...
4245604                                        0                        0
4245605                                        0                        0
4245606                                        0                        0
4245607                                       14                        0
4245610                                        0                        0

        Delay Late Aircraft Arrival (Minutes) Arrival Airport
9                                           0             ATL
11                                          0             ATL
20                                          0             ATL
23                                          0             ATL
34                                          0             ATL
...                                       ...             ...
4245604                                     0             TPA
4245605                                     0             TPA
4245606                                     0             TPA
4245607                                     0             TPA
4245610                                     0             TPA

[1288202 rows x 18 columns]>

In [8]:
f_df.to_csv('ar.csv')

In [22]:
arr = pd.read_csv(r'C:\Users\dharu\Documents\Studies\Q7\DS672\Data\arr.csv')

In [27]:
arr

,V1,CarrierCode,DateMMDDYYYY,FlightNumber,TailNumber,OriginAirport,ScheduledArrivalTime,ActualArrivalTime,ScheduledElapsedTimeMinutes,ActualElapsedTimeMinutes,...,WheelsonTime,TaxiIntimeMinutes,DelayCarrierMinutes,DelayWeatherMinutes,DelayNationalAviationSystemMinutes,DelaySecurityMinutes,DelayLateAircraftArrivalMinutes,ArrivalAirport,ArrTime,zipcode
0,9,AA,1/1/2016,1116,N005AA,LAX,6:13:00,5:57:00,253,232,...,5:48:00,9,0,0,0,0,0,ATL,6,30320
1,11,AA,1/1/2016,1249,N027AA,LAX,17:17:00,17:15:00,257,248,...,17:10:00,5,0,0,0,0,0,ATL,17,30320
2,20,AA,1/1/2016,2319,N4XBAA,ORD,21:35:00,21:25:00,121,113,...,21:08:00,17,0,0,0,0,0,ATL,21,30320
3,23,AA,1/1/2016,2513,N020AA,LAX,23:15:00,23:18:00,255,227,...,23:12:00,6,0,0,0,0,0,ATL,23,30320
4,34,AA,1/1/2017,909,N3FVAA,ORD,17:56:00,17:50:00,116,113,...,17:41:00,9,0,0,0,0,0,ATL,17,30320
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1288197,4245604,UA,12/31/2020,1444,N75425,IAH,20:21:00,20:10:00,126,114,...,20:06:00,4,0,0,0,0,0,TPA,20,33607
1288198,4245605,UA,12/31/2020,1538,N69818,ORD,12:31:00,12:20:00,161,155,...,12:16:00,4,0,0,0,0,0,TPA,12,33607
1288199,4245606,UA,12/31/2020,2002,N489UA,IAD,11:22:00,11:01:00,147,136,...,10:57:00,4,0,0,0,0,0,TPA,11,33607
1288200,4245607,UA,12/31/2020,2067,N38268,IAH,17:46:00,18:13:00,126,140,...,18:09:00,4,13,0,14,0,0,TPA,17,33607
1288201,4245610,UA,12/31/2020,2158,N37456,ORD,17:51:00,17:59:00,161,161,...,17:55:00,4,0,0,0,0,0,TPA,17,33607

In [28]:
arr = arr.rename(columns = {'DateMMDDYYYY':'date','ArrTime':'time','zipcode':'city'} )

In [29]:
arr

,V1,CarrierCode,date,FlightNumber,TailNumber,OriginAirport,ScheduledArrivalTime,ActualArrivalTime,ScheduledElapsedTimeMinutes,ActualElapsedTimeMinutes,...,WheelsonTime,TaxiIntimeMinutes,DelayCarrierMinutes,DelayWeatherMinutes,DelayNationalAviationSystemMinutes,DelaySecurityMinutes,DelayLateAircraftArrivalMinutes,ArrivalAirport,time,city
0,9,AA,1/1/2016,1116,N005AA,LAX,6:13:00,5:57:00,253,232,...,5:48:00,9,0,0,0,0,0,ATL,6,30320
1,11,AA,1/1/2016,1249,N027AA,LAX,17:17:00,17:15:00,257,248,...,17:10:00,5,0,0,0,0,0,ATL,17,30320
2,20,AA,1/1/2016,2319,N4XBAA,ORD,21:35:00,21:25:00,121,113,...,21:08:00,17,0,0,0,0,0,ATL,21,30320
3,23,AA,1/1/2016,2513,N020AA,LAX,23:15:00,23:18:00,255,227,...,23:12:00,6,0,0,0,0,0,ATL,23,30320
4,34,AA,1/1/2017,909,N3FVAA,ORD,17:56:00,17:50:00,116,113,...,17:41:00,9,0,0,0,0,0,ATL,17,30320
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1288197,4245604,UA,12/31/2020,1444,N75425,IAH,20:21:00,20:10:00,126,114,...,20:06:00,4,0,0,0,0,0,TPA,20,33607
1288198,4245605,UA,12/31/2020,1538,N69818,ORD,12:31:00,12:20:00,161,155,...,12:16:00,4,0,0,0,0,0,TPA,12,33607
1288199,4245606,UA,12/31/2020,2002,N489UA,IAD,11:22:00,11:01:00,147,136,...,10:57:00,4,0,0,0,0,0,TPA,11,33607
1288200,4245607,UA,12/31/2020,2067,N38268,IAH,17:46:00,18:13:00,126,140,...,18:09:00,4,13,0,14,0,0,TPA,17,33607
1288201,4245610,UA,12/31/2020,2158,N37456,ORD,17:51:00,17:59:00,161,161,...,17:55:00,4,0,0,0,0,0,TPA,17,33607

In [33]:
print (arr.dtypes)
print (we.dtypes)

V1                                             int64
CarrierCode                                   object
date                                  datetime64[ns]
FlightNumber                                   int64
TailNumber                                    object
OriginAirport                                 object
ScheduledArrivalTime                          object
ActualArrivalTime                             object
ScheduledElapsedTimeMinutes                    int64
ActualElapsedTimeMinutes                       int64
ArrivalDelayMinutes                            int64
WheelsonTime                                  object
TaxiIntimeMinutes                              int64
DelayCarrierMinutes                            int64
DelayWeatherMinutes                            int64
DelayNationalAviationSystemMinutes             int64
DelaySecurityMinutes                           int64
DelayLateAircraftArrivalMinutes                int64
ArrivalAirport                                object
time                                           int64
city                                           int64
dtype: object
date                 datetime64[ns]
time                          int64
maxtempC                      int64
mintempC                      int64
totalSnow_cm                float64
sunHour                     float64
uvIndex                       int64
moon_illumination             int64
moonrise                     object
moonset                      object
sunrise                      object
sunset                       object
DewPointC                     int64
FeelsLikeC                    int64
HeatIndexC                    int64
WindChillC                    int64
WindGustKmph                  int64
cloudcover                    int64
humidity                      int64
precipMM                    float64
pressure                      int64
tempC                         int64
visibility                    int64
winddirDegree                 int64
windspeedKmph                 int64
city                          int64
dtype: object

In [32]:
a = arr['date']
a =  pd.to_datetime(a,format = '%m/%d/%Y')
arr['date'] = a
b = we['date']
b =  pd.to_datetime(b,format = '%m/%d/%y')
we['date'] = b

In [34]:
result1 = pd.merge( arr, we, on = ["city", "date","time"])

In [35]:
result1

,V1,CarrierCode,date,FlightNumber,TailNumber,OriginAirport,ScheduledArrivalTime,ActualArrivalTime,ScheduledElapsedTimeMinutes,ActualElapsedTimeMinutes,...,WindChillC,WindGustKmph,cloudcover,humidity,precipMM,pressure,tempC,visibility,winddirDegree,windspeedKmph
0,9,AA,2016-01-01,1116,N005AA,LAX,6:13:00,5:57:00,253,232,...,0,15,22,87,0.0,1023,3,10,317,11
1,57876,DL,2016-01-01,1098,N127DL,SFO,6:20:00,6:11:00,265,262,...,0,15,22,87,0.0,1023,3,10,317,11
2,57917,DL,2016-01-01,1254,N551NW,LAX,6:00:00,5:47:00,245,231,...,0,15,22,87,0.0,1023,3,10,317,11
3,57943,DL,2016-01-01,1354,N1611B,LAX,6:54:00,6:41:00,244,226,...,0,15,22,87,0.0,1023,3,10,317,11
4,1106367,NK,2016-01-01,806,N506NK,LAS,6:20:00,6:19:00,230,231,...,0,15,22,87,0.0,1023,3,10,317,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1288197,4245586,UA,2019-12-31,1930,N77530,SFO,5:39:00,5:23:00,295,289,...,16,24,21,64,0.0,1017,16,10,340,17
1288198,4245588,UA,2019-12-31,2002,N445UA,IAD,10:49:00,10:58:00,149,159,...,17,23,12,50,0.0,1019,17,10,203,17
1288199,4245592,UA,2019-12-31,2389,N38403,IAH,10:51:00,10:30:00,130,110,...,17,23,12,50,0.0,1019,17,10,203,17
1288200,4245595,UA,2020-12-31,360,N832UA,IAD,20:26:00,20:06:00,146,134,...,23,41,40,64,0.0,1018,23,10,134,22
1288201,4245604,UA,2020-12-31,1444,N75425,IAH,20:21:00,20:10:00,126,114,...,23,41,40,64,0.0,1018,23,10,134,22

In [36]:
result1.to_csv('arrival_merged.csv')